version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "braincraft"
    assignees:
      - "braincraft"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
    groups:
      # Group TypeScript-related dependencies
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      # Group testing dependencies
      testing:
        patterns:
          - "jest"
          - "@jest/*"
          - "cross-env"
      # Group development dependencies
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    reviewers:
      - "braincraft"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
    reviewers:
      - "braincraft"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    groups:
      # Group GitHub Actions updates
      actions:
        patterns:
          - "*"
