name: Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation", "good-first-issue"]
assignees:
  - braincraft
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README.md
        - Code comments
        - API documentation
        - Setup/Installation guide
        - Usage examples
        - Contributing guide
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        File: README.md
        Section: Installation
        Line numbers: 45-52
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect information
        - Missing information
        - Unclear/confusing
        - Outdated information
        - Broken links
        - Formatting issues
        - Typos/grammar
        - Missing examples
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say?
      render: markdown

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Improvement
      description: How should it be improved?
      render: markdown

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about this documentation issue?
