name: Branch Protection

on:
  push:
    branches: [ main ]

jobs:
  check-author:
    name: Check Push Authorization
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Check if push is authorized
      run: |
        echo "Push to main branch detected"
        echo "Author: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"
        
        # Allow pushes from the repository owner or specific authorized users
        AUTHORIZED_USERS=("braincraft" "Asif1405")  # Add your GitHub usernames here
        
        USER_AUTHORIZED=false
        for user in "${AUTHORIZED_USERS[@]}"; do
          if [[ "${{ github.actor }}" == "$user" ]]; then
            USER_AUTHORIZED=true
            break
          fi
        done
        
        if [[ "$USER_AUTHORIZED" == "true" ]]; then
          echo "✅ Push authorized for user: ${{ github.actor }}"
        else
          echo "❌ Direct push to main branch is not allowed for user: ${{ github.actor }}"
          echo "Please create a pull request instead."
          exit 1
        fi

    - name: Validate push context
      run: |
        # Additional checks for merge context
        if [[ "${{ github.event.head_commit.message }}" == *"Merge pull request"* ]]; then
          echo "✅ This appears to be a PR merge"
        elif [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
          echo "✅ This is an automated action"
        elif [[ "${{ contains(github.event.head_commit.message, '[skip-protection]') }}" == "true" ]]; then
          echo "✅ Protection bypass requested in commit message"
        else
          echo "ℹ️ Direct push detected - additional validation may be required"
        fi

  notify-protection:
    name: Notify Protection Status
    runs-on: ubuntu-latest
    needs: [check-author]
    if: always() && github.ref == 'refs/heads/main'
    
    steps:
    - name: Send notification
      uses: actions/github-script@v7
      with:
        script: |
          const wasAuthorized = '${{ needs.check-author.result }}' === 'success';
          const actor = '${{ github.actor }}';
          const sha = '${{ github.sha }}';
          
          if (!wasAuthorized) {
            // Create an issue to track unauthorized push attempts
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Unauthorized push attempt to main branch`,
              body: `
              ## Unauthorized Push Detected
              
              **User:** @${actor}
              **Commit:** ${sha}
              **Time:** ${new Date().toISOString()}
              
              ### Action Required
              - [ ] Review the attempted changes
              - [ ] Create proper PR if changes are valid
              - [ ] Update branch protection rules if needed
              
              ### Prevention
              This push was blocked by branch protection workflow.
              Future pushes should go through pull request process.
              `,
              labels: ['security', 'branch-protection']
            });
          } else {
            console.log(`✅ Authorized push by ${actor} was allowed`);
          }
